#!/bin/sh

ARGENT_LOADER="/usr/bin/xdg-open"
ARGENT_URL=${ARGENT_URL:-http://www.argentlinux.io?install_welcome=1}

# load Argent URL
[[ -x "${ARGENT_LOADER}" ]] && ${ARGENT_LOADER} ${ARGENT_URL} &

# remove myself from autostart
rm ~/.config/autostart/argent-welcome-loader.desktop -f
